### ISSUE TITLE
Points to work in

### ISSUE THREAD

**Issue by alanggreen** [FirstLegoLeague/Coordination#10]
This is an initial list of issues that I feel needs to be addressed before this project can be used in place of the existing labview based package. The list was created by a group of head refs in Israel that have quite a bit of experience using the existing software.

I have grouped the items into Server, Client and Display
# Server

1. Need a simple, single file installation (or even better, one executable to run).
2. Need security/access control. If we are using wireless for tablets, we don't want to rely in the wireless password for access control.
3. Must be able to view ranking of team scores. Be able to sort by team name, team number and score.
4. Need to have a way to verify scores entered already i.e. be able to see for a particular team, how they scored the missions. Must be able to change the missions scored.
5. Be able to start and stop the timer without interfering too much with the score entry. The motivation for this is that in our competitions the scorekeepers are the people who most often do the timer too.
6. Want to maintain the same start/end sounds as the existing software. Either change them or make the sound files configurable.
7. Have a way of seeing the ip address that the display / client devices need to enter. Many users will not have the technical abilities required to find the IP address.
8. Very important - the current method of getting the scores onto the display requires too many steps. Not sure why the  CHECK FOR NEW SCORES and REFRESH SCORES buttons are necessary. Also, the BROADCAST button on the RANKING screen should have an "auto" setting for those tournaments that want it.

Additional issues that might already be possible 
1. Export results in format supported by Judging Lite

# Client (score input screen)
1. Static field at top of page that always shows accumulated score so far
2. Remove settings left menu input - settings should only be available from admin
3. See whether entry screen can be more compact - less scrolling required

# Score Display screen
We feel that a lot of work is required here

1. View team scores from all rounds as well as high score
2. Display the maximum possible number of teams (this is configurable so the requirement is available already)
3. Display the team number and team name
4. Display should support different languages - Hebrew for us
5. Show sponsor logos
6. Need a way to check / show the state of application connectivity with the server (for troubleshooting)
7. There must not be a need to enter team information on this screen. Must come from team list on server.

**Comment by kmeesters** [comment]
This should be split and entered as separate issues in the respective repro (if not fixed already)
