### ISSUE TITLE
Messenger system for volunteers

### ISSUE THREAD

**Issue by kmeesters** [FirstLegoLeague/Coordination#8]
Option to send messages to refs, judges etc. Volunteers management.

**Comment by rikkertkoppes** [comment]
Why reinvent the wheel here? Just use a slack/whatsapp/chat/whatever? What is the use case that we need to run our own solution?

**Comment by kmeesters** [comment]
Good point, people were fixing my intercom today, hence this sprung to mind. But indeed, other solutions exist. Perhaps good to list them on our public website as well: a long with some use-cases.
only thing I can think of is: (1) grouping of volunteer per role (2) contact information (ie. whatsapp need to add contacts ) and (3) internet dependency (does not work at international events). 
But agreed, low prio, and existing stuff maybe there as well. Perhaps together with a team app?

**Comment by kmeesters** [comment]
We have agreed on Slack (for internal communication) and GitHub (for coding/issues)
